import type { NetworkSnapshot } from './types';

export const sampleSnapshot: NetworkSnapshot = {
  generatedAt: '2026-06-21T22:00:00+00:00',
  nodes: {
    local: {
      chainPeers: [
        {
          address: '146.103.42.59:24892',
          direction: 'OUTBOUND',
          handshakeStatus: 'COMPLETED',
          nodeId: 'node-regxa',
          transport: 'IP',
          version: 'preview',
        },
        {
          address: '185.207.104.78:24892',
          direction: 'OUTBOUND',
          handshakeStatus: 'COMPLETED',
          nodeId: 'node-netcup',
          transport: 'I2P',
          version: 'preview',
        },
      ],
      dataPeers: [
        {
          address: '146.103.42.59:24894',
          direction: 'OUTBOUND',
          handshakeStatus: 'COMPLETED',
          transport: 'IP',
          version: 'preview',
        },
      ],
      info: {
        buildVersion: 'preview',
        nodeId: 'node-local',
      },
      label: 'L',
      name: 'Local',
      publicHost: null,
      role: 'participant',
      status: {
        height: 1200,
        numberOfConnections: 2,
        numberOfDataConnections: 1,
        syncPhase: 'OK',
      },
    },
    netcup: {
      chainPeers: [
        {
          address: 'local.example:24892',
          direction: 'INBOUND',
          handshakeStatus: 'COMPLETED',
          nodeId: 'node-local',
          transport: 'I2P',
          version: 'preview',
        },
        {
          address: '146.103.42.59:24892',
          direction: 'OUTBOUND',
          handshakeStatus: 'COMPLETED',
          nodeId: 'node-regxa',
          transport: 'IP',
          version: 'preview',
        },
      ],
      dataPeers: [
        {
          address: '146.103.42.59:24894',
          direction: 'OUTBOUND',
          handshakeStatus: 'COMPLETED',
          transport: 'I2P',
          version: 'preview',
        },
      ],
      info: {
        buildVersion: 'preview',
        nodeId: 'node-netcup',
      },
      label: 'N',
      name: 'Netcup',
      publicHost: '185.207.104.78',
      role: 'seed',
      status: {
        height: 1200,
        numberOfConnections: 2,
        numberOfDataConnections: 1,
        syncPhase: 'OK',
      },
    },
    regxa: {
      chainPeers: [
        {
          address: 'local.example:24892',
          direction: 'INBOUND',
          handshakeStatus: 'COMPLETED',
          nodeId: 'node-local',
          transport: 'IP',
          version: 'preview',
        },
        {
          address: '185.207.104.78:24892',
          direction: 'INBOUND',
          handshakeStatus: 'COMPLETED',
          nodeId: 'node-netcup',
          transport: 'IP',
          version: 'preview',
        },
      ],
      dataPeers: [
        {
          address: 'local.example:24894',
          direction: 'INBOUND',
          handshakeStatus: 'COMPLETED',
          transport: 'IP',
          version: 'preview',
        },
      ],
      info: {
        buildVersion: 'preview',
        nodeId: 'node-regxa',
      },
      label: 'R',
      name: 'Regxa',
      publicHost: '146.103.42.59',
      role: 'seed',
      status: {
        height: 1200,
        numberOfConnections: 2,
        numberOfDataConnections: 1,
        syncPhase: 'OK',
      },
    },
  },
  topology: {
    edges: [
      {
        count: 2,
        kind: 'IP_CHAIN',
        samples: [
          {
            address: '146.103.42.59:24892',
            direction: 'OUTBOUND',
            nodeId: 'node-regxa',
            reportedBy: 'local',
            transport: 'IP',
            version: 'preview',
          },
          {
            address: 'local.example:24892',
            direction: 'OUTBOUND',
            nodeId: 'node-local',
            reportedBy: 'regxa',
            transport: 'IP',
            version: 'preview',
          },
        ],
        source: 'L',
        target: 'R',
      },
      {
        count: 2,
        kind: 'IP_CHAIN',
        samples: [
          {
            address: '146.103.42.59:24892',
            direction: 'OUTBOUND',
            nodeId: 'node-regxa',
            reportedBy: 'netcup',
            transport: 'IP',
            version: 'preview',
          },
          {
            address: '185.207.104.78:24892',
            direction: 'INBOUND',
            nodeId: 'node-netcup',
            reportedBy: 'regxa',
            transport: 'IP',
            version: 'preview',
          },
        ],
        source: 'N',
        target: 'R',
      },
      {
        count: 1,
        kind: 'I2P_CHAIN',
        samples: [
          {
            address: '185.207.104.78:24892',
            direction: 'OUTBOUND',
            nodeId: 'node-netcup',
            reportedBy: 'local',
            transport: 'I2P',
            version: 'preview',
          },
        ],
        source: 'L',
        target: 'N',
      },
      {
        count: 2,
        kind: 'IP_DATA',
        samples: [
          {
            address: '146.103.42.59:24894',
            direction: 'OUTBOUND',
            reportedBy: 'local',
            transport: 'IP',
            version: 'preview',
          },
          {
            address: 'local.example:24894',
            direction: 'INBOUND',
            reportedBy: 'regxa',
            transport: 'IP',
            version: 'preview',
          },
        ],
        source: 'L',
        target: 'R',
      },
      {
        count: 1,
        kind: 'I2P_DATA',
        samples: [
          {
            address: '146.103.42.59:24894',
            direction: 'OUTBOUND',
            reportedBy: 'netcup',
            transport: 'I2P',
            version: 'preview',
          },
        ],
        source: 'N',
        target: 'R',
      },
    ],
    extraNodes: {},
    graphNodes: {
      L: {
        chainCount: 2,
        dataCount: 1,
        height: 1200,
        id: 'L',
        kind: 'operator',
        label: 'L',
        name: 'Local',
        observedBy: [],
        peerCount: 3,
        role: 'participant',
        status: 'OK',
        version: 'preview',
      },
      N: {
        chainCount: 2,
        dataCount: 1,
        height: 1200,
        host: '185.207.104.78',
        id: 'N',
        kind: 'operator',
        label: 'N',
        name: 'Netcup',
        observedBy: [],
        peerCount: 3,
        role: 'seed',
        status: 'OK',
        version: 'preview',
      },
      R: {
        chainCount: 2,
        dataCount: 1,
        height: 1200,
        host: '146.103.42.59',
        id: 'R',
        kind: 'operator',
        label: 'R',
        name: 'Regxa',
        observedBy: [],
        peerCount: 3,
        role: 'seed',
        status: 'OK',
        version: 'preview',
      },
    },
    namedLabels: {
      local: 'L',
      netcup: 'N',
      regxa: 'R',
    },
  },
};
